version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    volumes:
      - mysql_volume:/app/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=everyide
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
    ports:
      - "3306:3306"
    networks:
      - 8am_net
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  backend:
    container_name: backend
    ports:
      - "8000:8000"
    image: jamiejay/everyide
    volumes:
      - 8am_images:/app/8am/images
    networks:
      - 8am_net
    depends_on:
      - mysql
      - zookeeper
      - kafka
    entrypoint: /wait-for-services.sh
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/everyide

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    networks:
      - 8am_net

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "3001:3001"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:3000
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:3001
    networks:
      - 8am_net

networks:
  8am_net:
    driver: bridge

volumes:
  mysql_volume:
    driver: local
  8am_images:
    driver: local
